This commit fixes several incorrect hc* libraries include path, change hcc_path to hcc_home and comment out the unsupported hcblas routines.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -372,23 +372,23 @@ else
   # Set up which gcc nvcc should use as the host compiler
   while true; do
     fromuser=""
-    if [ -z "$HCC_PATH" ]; then
+    if [ -z "$HCC_HOME" ]; then
       default_hcc_compiler_path=/opt/rocm/hcc
-      read -p "Please specify which hcc compiler should. [Default is $default_hcc_compiler_path]: " HCC_PATH
+      read -p "Please specify which hcc compiler should. [Default is $default_hcc_compiler_path]: " HCC_HOME
       fromuser="1"
-      if [ -z "$HCC_PATH" ]; then
-        HCC_PATH=$default_hcc_compiler_path
+      if [ -z "$HCC_HOME" ]; then
+        HCC_HOME=$default_hcc_compiler_path
       fi
     fi
-    if [ -e "$HCC_PATH" ]; then
-      export HCC_PATH
+    if [ -e "$HCC_HOME" ]; then
+      export HCC_HOME
       break
     fi
-    echo "Invalid hcc path. ${HCC_PATH} cannot be found" 1>&2
+    echo "Invalid hcc path. ${HCC_HOME} cannot be found" 1>&2
     if [ -z "$fromuser" ]; then
       exit 1
     fi
-    HCC_PATH=""
+    HCC_HOME=""
     # Retry
   done 
 fi
