Fix Bugs and Remove Hardcoded Paths in SE
- Fix bugs which arised during hipifying cufft api containing files.
- Update configure to support input of libhipfft.so paths and include
  files which were hardcoded before.
- HipTF built successfully with hipfft apis in NV Stack

NOTE: Make sure to provide libhipfft_nvcc.so which is generated from libcufft.so and hipfft_nvcc.o
      in NVCC Platform and libhipfft_hc.so which is generated from libhcfft.so and hipfft_hc.o
      hipfft_nvcc.o and hipfft_hc.o are the object files of the cc files containing the definitions
      of the hip apis corresponding to their platforms.

hiptensorflow: hip-stream-executor

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -120,6 +120,52 @@ while true; do
   # Retry
 done
 
+# Set path of libhipfft.so  
+while true; do
+  fromuser=""
+  if [ -z "$HIPFFT_SO_PATH" ]; then
+    default_hipfft_so_path= /opt/rocm/hip/
+    read -p "Please specify the location where libhipfft.so is present. [Default is $default_hipfft_so_path]: " HIPFFT_SO_PATH
+    fromuser="1"
+    if [ -z "$HIPFFT_SO_PATH" ]; then
+      HIPFFT_SO_PATH=$default_hipfft_so_path
+    fi
+  fi
+  if [ -e "$HIPFFT_SO_PATH" ]; then
+    export HIPFFT_SO_PATH
+    break
+  fi
+  echo "Invalid libhipfft.so path. ${HIPFFT_SO_PATH} cannot be found" 1>&2
+  if [ -z "$fromuser" ]; then
+    exit 1
+  fi
+  HIPFFT_SO_PATH=""
+  # Retry
+done
+
+# Set path of hipFFT include files   
+while true; do
+  fromuser=""
+  if [ -z "$HIPFFT_INCLUDE_PATH" ]; then
+    default_hipfft_include_path= /opt/rocm/hip/include 
+    read -p "Please specify the location where hipfft include files are present. [Default is $default_hipfft_include_path]: " HIPFFT_INCLUDE_PATH
+    fromuser="1"
+    if [ -z "$HIPFFT_INCLUDE_PATH" ]; then
+      HIPFFT_INCLUDE_PATH=$default_hipfft_include_path
+    fi
+  fi
+  if [ -e "$HIPFFT_INCLUDE_PATH" ]; then
+    export HIPFFT_INCLUDE_PATH
+    break
+  fi
+  echo "Invalid path to hipfft include files. ${HIPFFT_INCLUDE_PATH} cannot be found" 1>&2
+  if [ -z "$fromuser" ]; then
+    exit 1
+  fi
+  HIPFFT_INCLUDE_PATH=""
+  # Retry
+done
+
 # Find out where the CUDA toolkit is installed
 OSNAME=`uname -s`
 
