Remove hardcoded Eigen path from workspace and add user specific eigen path to configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -162,6 +162,30 @@ while true; do
   # Retry
 done
 
+while true; do
+  fromuser=""
+  if [ -z "$HIP_EIGEN_PATH" ]; then
+    default_hip_eigen_path=/opt/rocm/hipeigen
+    read -p "Please specify the location of hipEigen. [Default is $default_hip_eigen_path]: " HIP_EIGEN_PATH
+    fromuser="1"
+    if [ -z "$HIP_EIGEN_PATH" ]; then
+      HIP_EIGEN_PATH=$default_hip_eigen_path
+    fi
+  fi
+  if [ -e "$HIP_EIGEN_PATH" ]; then
+    export HIP_EIGEN_PATH
+    break
+  fi
+  echo "Invalid hip_eigen path. ${HIP_EIGEN_PATH} cannot be found" 1>&2
+  if [ -z "$fromuser" ]; then
+    exit 1
+  fi
+  HIP_EIGEN_PATH=""
+  # Retry
+done
+
+perl -pi -e "s,EIGEN_PATH = ([\\a-z]+\s+\d*),EIGEN_PATH = \"${HIP_EIGEN_PATH}\"\n,s" tensorflow/workspace.bzl
+
 # Find out where the CUDA toolkit is installed
 OSNAME=`uname -s`
 if [ "$default_gpu_device" == "NVIDIA" ]; then
@@ -324,12 +348,11 @@ EOF
   done
 else
   #AMD configuration path
-  echo "Add code for AMD PATH"
   # Set up which gcc nvcc should use as the host compiler
   while true; do
     fromuser=""
     if [ -z "$HCC_COMPILER_PATH" ]; then
-      default_hcc_compiler_path="/opt/rocm/hcc"
+      default_hcc_compiler_path=/opt/rocm/hcc
       read -p "Please specify which hcc compiler should. [Default is $default_hcc_compiler_path]: " HCC_COMPILER_PATH
       fromuser="1"
       if [ -z "$HCC_COMPILER_PATH" ]; then
@@ -340,17 +363,13 @@ else
       export HCC_COMPILER_PATH
       break
     fi
-    echo "Invalid gcc path. ${HCC_COMPILER_PATH} cannot be found" 1>&2
+    echo "Invalid hcc path. ${HCC_COMPILER_PATH} cannot be found" 1>&2
     if [ -z "$fromuser" ]; then
       exit 1
     fi
     HCC_COMPILER_PATH=""
     # Retry
   done 
-  TF_CUDA_VERSION = 7.5
-  export TF_CUDA_VERSION
-  TF_CUDNN_VERSION = 5
-  export TF_CUDNN_VERSION
 fi
 bazel clean #--expunge
 bazel fetch //...
