Fix platform configuration using hipconfig

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,14 +8,14 @@ SOURCE_BASE_DIR=`pwd -P`
 popd > /dev/null
 
 ## Set up python-related environment settings
-VGA_DEVICE=$(lspci -v |grep VGA)
+VGA_DEVICE=$(hipconfig --platform)
 string='My long string';
 default_gpu_device="NO"
-if [[ $VGA_DEVICE == *"AMD"* ]]; then
+if [[ $VGA_DEVICE == "hcc" ]]; then
   default_gpu_device="AMD"
 fi
 
-if [[ $VGA_DEVICE == *"NVIDIA"* ]]; then
+if [[ $VGA_DEVICE == "nvcc" ]]; then
   default_gpu_device="NVIDIA"
 fi
 
@@ -372,23 +372,23 @@ else
   # Set up which gcc nvcc should use as the host compiler
   while true; do
     fromuser=""
-    if [ -z "$HCC_COMPILER_PATH" ]; then
+    if [ -z "$HCC_PATH" ]; then
       default_hcc_compiler_path=/opt/rocm/hcc
-      read -p "Please specify which hcc compiler should. [Default is $default_hcc_compiler_path]: " HCC_COMPILER_PATH
+      read -p "Please specify which hcc compiler should. [Default is $default_hcc_compiler_path]: " HCC_PATH
       fromuser="1"
-      if [ -z "$HCC_COMPILER_PATH" ]; then
-        HCC_COMPILER_PATH=$default_hcc_compiler_path
+      if [ -z "$HCC_PATH" ]; then
+        HCC_PATH=$default_hcc_compiler_path
       fi
     fi
-    if [ -e "$HCC_COMPILER_PATH" ]; then
-      export HCC_COMPILER_PATH
+    if [ -e "$HCC_PATH" ]; then
+      export HCC_PATH
       break
     fi
-    echo "Invalid hcc path. ${HCC_COMPILER_PATH} cannot be found" 1>&2
+    echo "Invalid hcc path. ${HCC_PATH} cannot be found" 1>&2
     if [ -z "$fromuser" ]; then
       exit 1
     fi
-    HCC_COMPILER_PATH=""
+    HCC_PATH=""
     # Retry
   done 
 fi
